# Generated by Django 3.2.12 on 2024-06-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='name',
            field=models.CharField(default='Year Election', max_length=300),
        ),
    ]
