# Generated by Django 3.2.12 on 2024-06-21 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20240621_0840'),
        ('voters', '0002_election_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.campus'),
        ),
        migrations.AlterField(
            model_name='election',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.campus'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.campus'),
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
    ]
