# Generated by Django 3.2.12 on 2024-06-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20240621_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.campus'),
        ),
    ]
